[package]
name = "aulua"
version = "0.12.0"
edition = "2024"
description = "AviUtl2 Lua script build & install tool"
repository = "https://github.com/karoterra/aviutl2-aulua"
license = "MIT"
readme = "README.md"
keywords = ["aviutl"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
regex = "1.13.1"
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml_ng = "0.10.0"
tempfile = "3.27.0"
thiserror = "2.0.20"
zip = "8.6.0"

[dev-dependencies]
rstest = "0.26.1"
