name: Release Windows Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --release

      - name: Install cargo-about
        run: cargo install --locked cargo-about

      - name: Generate NOTICE.html
        run: cargo about generate about.hbs -o NOTICE.html

      - name: Prepare release files
        run: |
          mkdir release
          copy target/release/aulua.exe release/
          copy README.md release/
          copy LICENSE release/
          copy NOTICE.html release/

      - name: Create zip archive
        run: |
          powershell Compress-Archive -Path release/* -DestinationPath aulua-${{ github.ref_name }}-windows.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: aulua-${{ github.ref_name }}-windows.zip
          generate_release_notes: true
